<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\ExtendedImportExport;

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Helpers\Authorization;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\Test;
use Jefferson49\Webtrees\Module\WebtreesApi\WebtreesApi;

use function e;


/**
 * @var string $title
 * @var bool   $pretty_urls
 * @var bool   $use_hash
 * @var string $webtrees_api_token
 * @var string $webtrees_api_url
 * @var string $pretty_webtrees_api_url
 */

if ($use_hash OR ($webtrees_api_token === '')) {
	$text_shown_for_webtrees_api_token = '';
}
else {
	$text_shown_for_webtrees_api_token = $webtrees_api_token;
}

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<form method="post" id="settings-form">
	<?= csrf_field() ?>
	<input type="hidden" name="save" id="save" value="1">

	<div class="h4">
		<?= I18N::translate('webtrees API URL') ?>	
	</div>
	<div class="row">
		<label class="col-sm-3 col-form-label wt-page-options-label">
			<?= MoreI18N::xlate('URL') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<span class="input-group-text"><?= e($webtrees_api_url) ?></span>
		</div>		
	</div>
	<div class="row">
		<label class="col-sm-3 col-form-label wt-page-options-label">
			<?= I18N::translate('Pretty URL') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<span class="input-group-text"><?= e($pretty_webtrees_api_url) ?></span>
		</div>		
	</div>

	<div class="row mb-3"><?= view('icons/spacer') ?></div>
	<div class="h4">
		<?= I18N::translate('API Test') ?>
	</div>		
	<?php if ($pretty_urls) : ?>
		<div class="row mb-3">
			<div class="col">
				<a href="<?= e(route(Test::class)) ?>" type="submit" class="btn btn-secondary">
					<?= MoreI18N::xlate('Test webtrees API') ?>
				</a>
			</div>		
		</div>
	<?php else : ?>
		<div class="row mb-3">
			<div class="alert alert-warning">
				<?= I18N::translate('The API can only be tested with "pretty" URLs enabled. Check the <a href="https://webtrees.net/faq/urls/" target="_blank">webtrees documentation</a> about how to enable "pretty" URLs.') ?>
			</div>
		</div>
	<?php endif	?>

	<div class="row mb-3"><?= view('icons/spacer') ?></div>

	<div class="h4">
		<?= I18N::translate('Settings for the API key') ?>
	</div>
	<p><?= I18N::translate('An authorization key is needed if the API shall be used.') ?></p>
	<div class="row mb-3">
		<?php if (!$uses_https) : ?>
			<div class="alert alert-danger">
				<?= I18N::translate('Currently, webtrees does not use the HTTPS protocol. It is urgently recommended to use HTTPS in order to ensure the encryption of the authorization key within API requests. HTTPS can be activated by changing "base_url" in the "config.ini.php". Currently, "base_url" does not start with "https://".') ?>
			</div>
		<?php endif ?>
		<?php if ($webtrees_api_token !== '' && !$use_hash) : ?>
			<div class="alert alert-warning">
				<?= I18N::translate('Currently, the API authorization key is not encrypted. This option is less secure and should only be used in local environments with limited users. Otherwise, please activate encryption of the authorization key.') ?>
			</div>  
		<?php endif ?>
		<label class="col-sm-3 col-form-label wt-page-options-label">
			<?= I18N::translate('Current API authorization key') ?>
		</label>
		<?php if ($use_hash && ($webtrees_api_token !== '')) : ?>
			<?php $text_shown_for_webtrees_api_token = I18N::translate('The API authorization key cannot be shown, because encryption is activated. If you forgot the key, you have to create a new key.')  ?>
		<?php elseif ($webtrees_api_token === '') : ?>
			<?php $text_shown_for_webtrees_api_token = I18N::translate('The API authorization key has not been set yet')  ?>
		<?php else : ?>
			<?php $text_shown_for_webtrees_api_token = $webtrees_api_token  ?>
		<?php endif ?>
		<div class="col-sm-9 wt-page-options-value">
			<span class="input-group-text"><?= e($text_shown_for_webtrees_api_token) ?></span>
		</div>
	</div>				
	<div class="row mb-3">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="new_api_token">
			<?= I18N::translate('New API authorization key') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<?php if ($webtrees_api_token === '') : ?>
				<?php $new_api_token = Authorization::generateAuthKey(WebtreesApi::MINIMUM_API_KEY_LENGTH)  ?>
			<?php else : ?>
				<?php $new_api_token = '' ?>
			<?php endif ?>
			<input class="form-control" id="new_api_token" name="new_api_token" type="text" value="<?= $new_api_token ?>">
			<div class="form-text" id="new_api-key-description">
				<?= MoreI18N::xlate('Authorization keys must have a minimum length of %s characters.', WebtreesApi::MINIMUM_API_KEY_LENGTH) ?>
			</div>	</div>
		</div>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Activate encryption of the API authorization key') ?>
			</legend>
			<div class="col-sm-9">
			<?= view('components/checkbox', ['label' => I18N::translate('Activate'), 'name' => DownloadGedcomWithURL::PREF_USE_HASH, 'checked' => $use_hash]) ?>
				<div class="form-text">
					<?= I18N::translate('The encryption of the authorization key is more secure, because the authorization key is not visible to anyone and also encrypted in the database. However, the authorization key is not readible any more (e.g. for other administrators) and cannot be recovered if it is forgotten.'); ?>
				</div>
			</div>
		</div>
	</fieldset>		

	<div class="row mb-3">
		<div class="col">
			<p></p>
			<button type="submit" class="btn btn-primary">
				<?= view('icons/save') ?>
				<?= MoreI18N::xlate('save') ?>
			</button>
		</div>		
	</div>		
</form>	

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
</script>
<?php View::endpush() ?>