<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\WebtreesApi;

use DateTimeImmutable;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\CreateTokenModal;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\DeleteClient;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\EditClientAction;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\EditClientModal;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\RevokeToken;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\TestApi;
use Jefferson49\Webtrees\Module\WebtreesApi\OAuth2\Repositories\AccessTokenRepository;

use function e;


/**
 * @var string $title
 * @var bool   $pretty_urls
 * @var string $webtrees_api_token
 * @var string $webtrees_api_url
 * @var string $pretty_webtrees_api_url
 * @var string $mcp_url
 * @var string $pretty_mcp_url
 * @var string $access_token_url
 * @var string $pretty_access_token_url
 * @var array  $user_list
 * @var array  $clients
 * @var array  $client_identifiers
 * @var array  $access_tokens
 * @var array  $scope_identifiers
 * @var AccessTokenRepository $access_token_repository
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>
<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('webtrees API URL') ?>	
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= MoreI18N::xlate('URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($webtrees_api_url) ?></span>
	</div>		
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= I18N::translate('Pretty URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($pretty_webtrees_api_url) ?></span>
	</div>		
</div>	

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('MCP URL') ?>	
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= MoreI18N::xlate('URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($mcp_url) ?></span>
	</div>		
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= I18N::translate('Pretty URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($pretty_mcp_url) ?></span>
	</div>		
</div>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('OAuth2 Access Token URL') ?>	
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= MoreI18N::xlate('Access Token URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($access_token_url) ?></span>
	</div>		
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= I18N::translate('Pretty URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($pretty_access_token_url) ?></span>
	</div>		
</div>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('API Test') ?>
</div>		
<?php if ($pretty_urls) : ?>
	<div class="row mb-3">
		<div class="col">
			<a href="<?= e(route(TestApi::class)) ?>" type="submit" class="btn btn-secondary">
				<?= MoreI18N::xlate('Test webtrees API') ?>
			</a>
		</div>		
	</div>
<?php else : ?>
	<div class="row mb-3">
		<div class="alert alert-warning">
			<?= I18N::translate('The API can only be tested with "pretty" URLs enabled. Check the <a href="https://webtrees.net/faq/urls/" target="_blank">webtrees documentation</a> about how to enable "pretty" URLs.') ?>
		</div>
	</div>
<?php endif	?>

<div class="row mb-3">
	<?php if (!$uses_https) : ?>
		<div class="alert alert-danger">
			<?= I18N::translate('Currently, webtrees does not use the HTTPS protocol. It is urgently recommended to use HTTPS in order to ensure the encryption of the authorization key within API requests. HTTPS can be activated by changing "base_url" in the "config.ini.php". Currently, "base_url" does not start with "https://".') ?>
		</div>
	<?php endif ?>
</div>

<div class="h4">
	<?= I18N::translate('Client Credentials') ?>
</div>

<table
	class="table table-bordered table-sm wt-table-module-updates datatables d-none"
	<?= view('lists/datatables-attributes') ?>
	data-columns="<?= e(json_encode([
		null,
		null,
		null,
		null,
		null,
		['type' => 'html', 'searchable' => false],
		['type' => 'html', 'searchable' => false],
		['type' => 'html', 'searchable' => false],
	], JSON_THROW_ON_ERROR)) ?>"
>
	<caption class="visually-hidden">
		<?= $caption ?? I18N::translate('Client Credentials') ?>
	</caption>
	<thead>
		<tr>
			<th><?= I18N::translate('Client Identifier') ?></th>
			<th><?= I18N::translate('Client Secret') ?></th>
			<th><?= I18N::translate('Client Name') ?></th>
			<th><?= I18N::translate('Scopes') ?></th>
			<th><?= I18N::translate('Technical User') ?></th>
			<th><?= I18N::translate('Edit') ?></th>
			<th><?= I18N::translate('Delete') ?></th>
			<th><?= I18N::translate('Create Access Token') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($clients as $client) : ?>
			<tr>
				<!-- Client Identifier -->
				<td data-sort="<?= e($client->getIdentifier()) ?>">
					<?= e($client->getIdentifier()) ?>
				</td>
				<!-- Client Secret -->
				<td>
					<?= '****' ?>
				</td>
				<!-- Client Name -->
				<td data-sort="<?= e($client->getName()) ?>">
					<?= e($client->getName()) ?>
				</td>
				<!-- Scopes -->
				<?php $client_scopes = array_map(fn($scope) => $scope->getIdentifier(), $client->getScopes()) ?>
				<td>
					<?= e(implode(' ', $client_scopes)) ?>
				</td>
				<!-- Technical User -->
				<td data-sort="<?= e($user_list[$client->getTechnicalUserId()] ?? '') ?>">
					<?= e($user_list[$client->getTechnicalUserId()] ?? '') ?>
				</td>
				<!-- Edit -->
				<td data-sort="<?= '' ?>">
					<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal"
							data-wt-href="<?= e(route(EditClientModal::class, [
								'edit_client_action' => EditClientAction::EDIT_CLIENT_ACTION_EDIT,
								'client_identifier'  => $client->getIdentifier(),
								'client_secret_hash' => $client->getClientSecretHash(),
								'client_name'        => $client->getName(),
								'scope_identifiers'  => $scope_identifiers,
								'client_scopes'      => $client_scopes,
								'user_list'          => $user_list,
								'technical_user_id'  => $client->getTechnicalUserId(),
							]
						)) ?>">											
						<input class="btn btn-primary" type="submit" value="<?= MoreI18N::xlate('Edit') ?>">
					</a>
				</td>
				<!-- Delete -->
				<?php $client_has_tokens = !empty($access_token_repository->accessTokensForClient($client->getIdentifier())) ?>
				<td>
					<?php if (!$client_has_tokens) : ?>
						<a href="<?= e(route(DeleteClient::class, [
									'client_identifier' => $client->getIdentifier(),
								]
								)) ?>" type="submit" class="btn btn-primary">
							<?= MoreI18N::xlate('Delete') ?>
						</a>					
					<?php else : ?>
						<?= I18N::translate('Client has tokens assigned') ?>
					<?php endif ?>
				</td>				
				<!-- Create Access Token -->
				<td>
					<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" 
							data-wt-href="<?= e(route(CreateTokenModal::class, [
								'client_identifier'    => $client->getIdentifier(),
								'scope_identifiers'    => $client_scopes,
								'token_scopes'         => [],
								'expiration_intervals' => AccessTokenRepository::getExpirationIntervals(),
								'expiration_interval'  => AccessTokenRepository::DEFAULT_EXPIRATION_INTERVAL,
							]
						)) ?>">											
						<input class="btn btn-primary" type="submit" value="<?= MoreI18N::xlate('Create access token') ?>">
					</a>					
				</td>
			</tr>		
		<?php endforeach ?>						
	</tbody>
</table>
<button type="submit" class="btn btn-primary">
	<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" 
			data-wt-href="<?= e(route(EditClientModal::class, [
				'edit_client_action' => EditClientAction::EDIT_CLIENT_ACTION_ADD,
				'scope_identifiers'  => $scope_identifiers,
				'client_scopes'      => [],
				'user_list'          => $user_list,
			]
		)) ?>">											
		<input class="btn btn-primary" type="submit" value="<?= MoreI18N::xlate('Add client') ?>">
	</a>	
</button>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('Access Tokens') ?>
</div>
<p><?= I18N::translate(' Currently, the following access tokens are active, i.e. not expired yet.') ?></p>
<table
	class="table table-bordered table-sm wt-table-module-updates datatables d-none"
	<?= view('lists/datatables-attributes') ?>
	data-columns="<?= e(json_encode([
		null,
		null,
		null,
		null,
		null,
		['type' => 'html', 'searchable' => false],
	], JSON_THROW_ON_ERROR)) ?>"
>
	<caption class="visually-hidden">
		<?= $caption ?? I18N::translate('Access Tokens') ?>
	</caption>

	<thead>
		<tr>
			<th><?= MoreI18N::xlate('Access Token') ?></th>
			<th><?= I18N::translate('Client Identifier') ?></th>
			<th><?= I18N::translate('Scopes') ?></th>
			<th><?= I18N::translate('Expiration Date') ?></th>
			<th><?= I18N::translate('Revoked') ?></th>
			<th><?= I18N::translate('Revoke') ?></th>
		</tr>
	</thead>

	<tbody>		
		<?php foreach ($access_tokens as $token) : ?>
			<tr>
				<!-- Access Token -->
				<td data-sort="<?= e($token->getIdentifier()) ?>">
					<?= e('****' . $token->getIdentifier()) ?>
				</td>
				<!-- Client Identifier -->
				<td data-sort="<?= e($token->getClient()->getIdentifier()) ?>">
					<?= e($token->getClient()->getIdentifier()) ?>
				</td>
				<!-- Scopes -->
				<?php $token_scopes = array_map(fn($scope) => $scope->getIdentifier(), $token->getScopes()) ?>
				<td>
					<?= e(implode(' ', $token_scopes)) ?>
				</td>
				<!-- Expiration Date -->
				<td data-sort="<?= e($token->getExpiryDateTime()->format(DateTimeImmutable::ATOM)) ?>">
					<?= e($token->getExpiryDateTime()->format(DateTimeImmutable::ATOM)) ?>
				</td>
				<!-- Revoked -->
				<td data-sort="<?= e($token->isRevoked() ? MoreI18N::xlate('yes') : MoreI18N::xlate('no')) ?>">
					<?= e($token->isRevoked()  ? MoreI18N::xlate('yes') : MoreI18N::xlate('no')) ?>
				</td>
				<!-- Revoke -->
				<td>
					<?php if (!$token->isRevoked()) : ?>
						<a href="<?= e(route(RevokeToken::class, [
									'token_identifier' => $token->getIdentifier(),
								]
								)) ?>" type="submit" class="btn btn-primary">
							<?= MoreI18N::xlate('Revoke') ?>
						</a>
					<?php endif ?>
				</td>
			</tr>	
		<?php endforeach ?>
	</tbody>
</table>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('Explanation of Technical User (to define API/MCP access rights)') ?>
</div>
<p><?= I18N::translate('By selecting a (technical) user, the access rights for API/MCP requests can be specified. Any tree data requested with API/MCP is limited to the access rights of the specified (technical) user.') ?></p>
<p><?= I18N::translate('It is recommended to create a separate (technical) user, which is only used to define the API/MCP access rights. The maximum access role, wich is allowed for the (technical) user is limited to an "Editor". "Moderators" or "Administrators" are denied access during API/MCP requests.') ?></p>
<p><?= I18N::translate('If new records etc. are created with API/MCP, the data is created with the specified (technical) user. In order to have control about the changed data, it is not allowed that the selected (technical) user has "Automatically accept changes" activated. This ensures that a moderator can always reject unintended changes during a review of pending changes.') ?></p>

<?php View::push('javascript') ?>
<script>
	$('body').on('hidden.bs.modal', function () {
		location.reload();
	});	
</script>
<?php View::endpush() ?>
<?= view('modals/ajax') ?>