<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\ExtendedImportExport;

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\McpApi\McpApi;

use function e;


/**
 * @var string $title
 * @var bool   $pretty_urls
 * @var string $resources_URL
 * @var string $open_api_file
 */

?>
<title><?=e($title) ?></title>

<link rel="stylesheet" type="text/css" href="<?= e($resources_URL . '/css/swagger-ui.css') ?>">

<?php if (!$pretty_urls) : ?>
	<?= view('components/' . 'alert-danger', [
		'alert' => I18N::translate('The API can only be tested with "pretty" URLs enabled. Check the <a href="https://webtrees.net/faq/urls/" target="_blank">webtrees documentation</a> about how to enable "pretty" URLs.'),
	]) ?>
<?php else : ?>
	<div id="swagger-ui"></div>
<?php endif	?>

<?php View::push('javascript') ?>

<script src="<?= e($resources_URL . '/js/swagger-ui-bundle.js') ?>"></script>
<script src="<?= e($resources_URL . '/js/swagger-ui-standalone-preset.js') ?>"></script>

<script>
	window.onload = function() {
		const ui = SwaggerUIBundle({
			url: "<?= e($resources_URL . '/OpenApi/OpenApi.json') ?>",
			dom_id: '#swagger-ui',
			presets: [
				SwaggerUIBundle.presets.apis,
				SwaggerUIStandalonePreset
			]
		});
		window.ui = ui;
	};
</script>

<?php View::endpush() ?>