<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\WebtreesApi;

use Fisharebest\Webtrees\I18N;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\EditClientAction;

/**
 * @var string        $client_name
 * @var string        $client_identifier
 * @var string        $client_secret
 * @var array<string> $client_scopes
 * @var array<string> $scope_identifiers
 * @var int           $technical_user_id
 * @var array<string> $user_list
 * @var string        $edit_client_action
*/

?>

<div class="row mb-3">
    <input type="hidden" name="edit_client_action" id="edit_client_action" value="<?= e($edit_client_action) ?>">
    <label class="col-form-label col-sm-3" for="client_identifier">
        <?= I18N::translate('Client Identifier') ?>
    </label>
    <div class="col-sm-9">
        <input class="form-control" type="text" id="client_identifier" name="client_identifier" value="<?= e($client_identifier) ?>" dir="auto" required="required" <?= $edit_client_action === EditClientAction::EDIT_CLIENT_ACTION_EDIT ? 'disabled' : '' ?>>
        <input type="hidden" id="client_identifier" name="client_identifier" value="<?= e($client_identifier) ?>" <?= $edit_client_action !== EditClientAction::EDIT_CLIENT_ACTION_EDIT ? 'disabled' : '' ?>>
    </div>
    <label class="col-form-label col-sm-3" for="client_name">
        <?= I18N::translate('Client Name') ?>
    </label>
    <div class="col-sm-9">
        <input class="form-control" type="text" id="client_name" name="client_name" required="required" value="<?= e($client_name) ?>">
    </div>
    <label class="col-form-label col-sm-3" for="client_secret">
        <?= I18N::translate('Client Secret') ?>
    </label>
    <div class="col-sm-9">
        <input class="form-control" type="text" id="client_secret" name="client_secret" required="required" value="<?= e($client_secret) ?>">
    </div>
    <label class="col-form-label col-sm-3" for="client_scopes">
        <?= I18N::translate('Scopes') ?>
    </label>
    <div class="col-sm-9">
        <div class="input-group" required="required">
            <?= view('components/select', [
                    'name'     => 'client_scopes[]',
                    'id'       => 'client_scopes',
                    'selected' => $client_scopes,
                    'options'  => $scope_identifiers,
                    'class'    => 'tom-select'
                ]
            ) ?>
        </div>
    </div>
    <label class="col-form-label col-sm-3" for="technical_user_id">
        <?= I18N::translate('Technical User') ?>
    </label>
    <div class="col-sm-9">
        <div class="input-group" required="required">
            <?= view('components/select', [
                    'name'     => 'technical_user_id',
                    'id'       => 'technical_user_id',                    
                    'selected' => $technical_user_id,
                    'options'  => $user_list,
                ]) 
            ?>
        </div>
    </div>
</div>
