<?php

namespace Jefferson49\Webtrees\Module\WebtreesApi;

use Fisharebest\Webtrees\I18N;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\CreateKeysAction;

?>

<form method="post" action="<?= e(route(CreateKeysAction::class)) ?>" id="wt-modal-form">
    
    <?= view('modals/header', ['title' => I18N::translate('Create new private/public keys')]) ?>

    <div class="modal-body">
        <div class="row">
            <p class="alert alert-danger"><?= I18N::translate('Please confirm: Existing private/public keys will be deleted and replaced by new keys. Existing access tokens will be deleted, because they will not work with newly created keys.') ?></p>
        </div>        
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= I18N::translate('confirm') ?>
        </button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
            <?= view('icons/cancel') ?>
            <?= I18N::translate('cancel') ?>
        </button>
    </div>

    <?= csrf_field() ?>
</form>

<script>
    document.getElementById('wt-modal-form').addEventListener('submit', webtrees.createRecordModalSubmit);
</script>
